# Docker


# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
    - task: NeuVectorScan@3
      inputs:
        #scanType: 'external'
        #neuvectorScanner: 'Neuvector on Azure'
        #repository: node
        #tag: 12.18.1
        scanType: 'standalone'
        nvContainerRegistry: 'NeuVector Registry on Docker'
        nvRepository: 'neuvector/scanner'
        nvTag: 'latest'
        containerRegistry: 'Docker Hub'
        repository: 'library/alpine'
        tag: 'latest'
